/* ***** BEGIN LICENSE BLOCK *****
 * Distributed under the BSD license:
 *
 * Copyright (c) 2012, Ajax.org B.V.
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Ajax.org B.V. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AJAX.ORG B.V. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 * Contributor(s):
 * 
 *
 *
 * ***** END LICENSE BLOCK ***** */

/*
  THIS FILE WAS AUTOGENERATED BY mode_highlight_rules.tmpl.js (UUID: FF1825E8-6B1C-11D9-B883-000D93589AF6) */

/*******

  THIS FILE MIGHT NOT BE PERFECT, PARTICULARLY:

  IN DECIDING STATES TO TRANSITION TO,

  IGNORING WHITESPACE, 

  IGNORING GROUPS WITH ?:, 

  EXTENDING EXISTING MODES,

  GATHERING KEYWORDS, OR

  RULE PREFERENCE ORDER.

  ...But it's a good start from an existing *.tmlanguage file.

*******/

define(function(require, exports, module) {
"use strict";

var oop = require("../lib/oop");
var TextHighlightRules = require("./text_highlight_rules").TextHighlightRules;

var MakefileHighlightRules = function() {

    // regexp must not have capturing parentheses. Use (?:) instead.
    // regexps are ordered -> the first match is used

    this.$rules = 
        {
    "start": [
        {
            "token": [
                null,
                "variable.other.makefile"
            ],
            "regex": "^(\\w|[-_])+\\s*\\??=",
            "next": "state_1"
        },
        {
            "token": [
                null,
                "string.interpolated.backtick.makefile"
            ],
            "regex": "`",
            "next": "state_2"
        },
        {
            "token": [
                {
                    "0": {
                        "name": "punctuation.definition.comment.makefile"
                    }
                },
                "comment.line.number-sign.makefile"
            ],
            "regex": "#",
            "next": "state_3"
        },
        {
            "token": [
                "keyword.control.makefile",
                "keyword.control.makefile"
            ],
            "regex": "^(\\s*)\\b(\\-??include|ifeq|ifneq|ifdef|ifndef|else|endif|vpath|export|unexport|define|endef|override)\\b"
        },
        {
            "token": [
                [],
                {
                    "1": {
                        "name": "entity.name.function.makefile"
                    }
                },
                "meta.function.makefile"
            ],
            "regex": "^([^\\t ]+(\\s[^\\t ]+)*:(?!\\=))\\s*.*"
        }
    ],
    "state_1": [
        {
            "regex": "\\\\\\n"
        },
        {
            "token": "TODO",
            "regex": "$",
            "next": "start"
        }
    ],
    "state_2": [
        {
            "include": "source.shell"
        },
        {
            "token": "TODO",
            "regex": "`",
            "next": "start"
        }
    ],
    "state_3": [
        {
            "token": "punctuation.separator.continuation.makefile",
            "regex": "(?<!\\\\)\\\\$\\n", // ERROR: This contains a lookbehind, which JS does not support :("
        },
        {
            "token": "TODO",
            "regex": "$\\n?",
            "next": "start"
        }
    ]
}

    /*** START REPOSITORY RULES

END REPOSITORY RULES ***/
};

oop.inherits(MakefileHighlightRules, TextHighlightRules);

exports.MakefileHighlightRules = MakefileHighlightRules;
});